name: calculator

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  openapi:
    path: ./openapi

dev_dependencies:
  flutter_test:
    sdk: flutter

# Конфигурация Flutter
flutter:
  uses-material-design: true
  
  # Используем Google Fonts вместо локальных шрифтов для упрощения
  assets:
    - assets/fonts/
