name: Build and push backend image

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/calculator-backend
          tags: |
            type=raw,value=latest
            type=raw,value=sha-${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ansible Playbook to deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: deploy
          playbook: deploy-ansible-playbook.yaml
          options: |
            -i "${{ secrets.DEPLOY_SERVER_IP }},"
            -e "github_actor=${{ secrets.GHCR_USERNAME }}"
            -e "github_token=${{ secrets.GHCR_TOKEN }}"
            -u "${{ secrets.DEPLOY_SERVER_USER }}"
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          requirements: ansible-requirements.yaml
